-- V2：访问流水表。
--
-- 本脚本新增 visit_log 表，用于持久化短链访问流水。
-- V1__create_short_link.sql 已合入即只读，不得回头修改。
CREATE TABLE visit_log (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(16)   NOT NULL,
    referer    VARCHAR(2048),
    visited_at TIMESTAMP     NOT NULL
);

CREATE INDEX idx_visit_log_code_visited_at ON visit_log(code, visited_at DESC);
